# -Dspring.profiles.active=local
spring:
  mail:
    username: 3063400699@qq.com # 发送者的邮箱，必须是QQ邮箱
    password: vemfyuydtjlwdcih # 发送者邮箱的授权码，我将这个服务关闭了
---
pet-ship:
  images-path: D:\MixPet-main\images # 照片存储路径
  notice-path: D:\MixPet-main\notice # 公告存储路径
  chatImg-path: D:\MixPet-main\chatImg # 聊天图片存储路径
---
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句